name: Build unmpkg binary for arm64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set env
        run: |
          echo build_time=$(TZ=Asia/Shanghai date '+%Y%m%d%H%M') | tee -a $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Install packages
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            apt update && apt install clang cmake git -y
             git clone https://github.com/llvm/llvm-project.git --depth 1
             mkdir llvm-project/llvm/build
             cd llvm-project/llvm/build
             cmake .. -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr
             make -j8
             cd -
             tar -rf llvm.tar llvm-project
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: unmpkg
          body: |
            This is unmpkg static binary release.
            Build time: ${{ env.build_time }}
          prerelease: false
          files: |
            /home/runner/work/llvm-build/llvm.tar
